config = {
        "name": "mysql-source-connector-with-statement",
        "config": {
            "connector.class": "io.debezium.connector.mysql.MySqlConnector",
            "database.hostname": "mysql-database",
            "database.port": "3306",
            "database.user": "myuser",
            "database.password": "mypassword",
            "database.dbname": "mydb",
            "database.server.name": "azki_mysql_server",
            "database.server.id": "202511181456",
            "topic.prefix": "azki_mysql",
            "table.include.list": "mydb.users",
            "snapshot.mode": "initial-only",
            "tasks.max": "1",
            "key.converter": "org.apache.kafka.connect.storage.StringConverter",
            "key.converter.schemas.enable": "false",
            "value.converter": "io.confluent.connect.avro.AvroConverter",
            "value.converter.schemas.enable": "true",
            "value.converter.schema.registry.url": "http://schema-registry:8081",
            "database.history.kafka.bootstrap.servers": "kafka-broker-1:19092",
            "database.history.kafka.topic": "azki_mysql.schema-changes",
            "transforms": "unwrap",
            "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
            "transforms.unwrap.drop.tombstones": "false",
            "transforms.unwrap.add.fields": "op,source.ts_ms:EVENT_TS,ts_ms:KAFKA_EVENT_TS",
            "schema.history.internal.kafka.bootstrap.servers": "kafka-broker-1:19092",
            "schema.history.internal.kafka.topic": "schema-changes.mydb",
            "database.include.list": "mydb",
            "snapshot.select.statement.overrides": "mydb.users",
            "snapshot.select.statement.overrides.mydb.users": "select * from mydb.users where signup_date> '?'",
        }
    }